# permissions for end users to edit hostedcomets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostedcomet-editor-role
rules:
- apiGroups:
  - comet.cometbackup.com
  resources:
  - hostedcomets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - comet.cometbackup.com
  resources:
  - hostedcomets/status
  verbs:
  - get
