# permissions for end users to view hostedcomets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hostedcomet-viewer-role
rules:
- apiGroups:
  - comet.cometbackup.com
  resources:
  - hostedcomets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - comet.cometbackup.com
  resources:
  - hostedcomets/status
  verbs:
  - get
