---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-external-dns
  namespace: {{ .Release.Namespace }}
  # # If you're using Amazon EKS with IAM Roles for Service Accounts, specify the following annotation.
  # # Otherwise, you may safely omit it.
  # annotations:
  #   # Substitute your account ID and IAM service role name below.
  #   eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT-ID:role/IAM-SERVICE-ROLE-NAME
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}-external-dns
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: [""]
  resources: ["services","endpoints","pods"]
  verbs: ["get","watch","list"]
- apiGroups: ["extensions","networking.k8s.io"]
  resources: ["ingresses"]
  verbs: ["get","watch","list"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "list","watch"]
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get","watch","list"]
- apiGroups: ["externaldns.k8s.io"]
  resources: ["dnsendpoints"]
  verbs: ["get","watch","list"]
- apiGroups: ["externaldns.k8s.io"]
  resources: ["dnsendpoints/status"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Release.Name }}-external-dns-viewer
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Release.Name }}-external-dns
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-external-dns
  namespace: {{ .Release.Namespace }}