---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-external-dns
  namespace: {{ .Release.Namespace }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: {{ .Release.Name }}-external-dns
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-external-dns
      # # If you're using kiam or kube2iam, specify the following annotation.
      # # Otherwise, you may safely omit it.
      # annotations:
      #   iam.amazonaws.com/role: arn:aws:iam::ACCOUNT-ID:role/IAM-SERVICE-ROLE-NAME
    spec:
      serviceAccountName: {{ .Release.Name }}-external-dns
      containers:
      - name: external-dns
        image: k8s.gcr.io/external-dns/external-dns:v0.7.6
        args:
        - --source=crd
        - --source=node # will use nodes as source
        - --crd-source-apiversion=externaldns.k8s.io/v1alpha1  
        - --crd-source-kind=DNSEndpoint
        - --provider={{ .Values.externalDNS.provider }}
        - --fqdn-template={{ .Values.hostedZonePrefix }}.{{ .Values.hostedZone }}
        - --policy=upsert-only
        - --txt-prefix=txt-
        - --interval=30s
      securityContext:
        fsGroup: 65534 # For ExternalDNS to be able to read Kubernetes and AWS token files