---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Release.Name }} 
  serviceName: {{ .Release.Name }}
  replicas: {{ .Values.replicas | default 1 }}
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: {{ .Release.Name }} 
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: whoami
        image: traefik/whoami
        ports:
        - name: web
          containerPort: 80
  #       volumeMounts:
  #       - name: data
  #         mountPath: /var/lib/cometd
  # volumeClaimTemplates:
  # - metadata:
  #     name: data
  #   spec:
  #     accessModes: ["ReadWriteOnce"]
  #     storageClassName: "longhorn-static"
  #     resources:
  #       requests:
  #         storage: 32Gi
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Release.Name }}
spec:
  clusterIP: None
  selector:
    app: {{ .Release.Name }}