apiVersion: comet.cometbackup.com/v1
kind: HostedComet
metadata:
  name: hostedcomet-system
spec:
  region: us-east-1
  hostedZone: hostedsrv.net
  # Number of replicas the controller should deploy.
  # This maps directly to a StatefulSet with a matching number of replicas. Using replicas=3 will produce:
  #   us-east-1{a,b,c}.offsitenetwork.net
  replicas: 3
